name=Arduino_BME690
version=1.0.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
sentence=Allows you to read temperature, humidity, barometric pressure and gas resistance from a Bosch BME690 sensor.
paragraph=Built on top of Bosch Sensortec's bme69x low-level driver, wrapped in a simple, classic Arduino API.
category=Sensors
url=https://github.com/arduino-libraries/Arduino_BME690
architectures=*
includes=Arduino_BME690.h
